In [2]:
import pandas as pd

In [3]:
# df=pd.read_csv("E:\WALMART PROJECT\Walmart Data Analysis and Forcasting.csv")
# df=pd.read_csv("Clean Wellmart Data_set.csv")
df = pd.read_csv("Clean Wellmart Data_set.csv", parse_dates=['Date'])

In [4]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3

In [5]:
df.tail()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [6]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info

<bound method DataFrame.info of       Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  12-02-2010    1641957.44             1        38.51       2.548
2         1  19-02-2010    1611968.17             0        39.93       2.514
3         1  26-02-2010    1409727.59             0        46.63       2.561
4         1  05-03-2010    1554806.68             0        46.50       2.625
...     ...         ...           ...           ...          ...         ...
6430     45  28-09-2012     713173.95             0        64.88       3.997
6431     45  05-10-2012     733455.07             0        64.89       3.985
6432     45  12-10-2012     734464.36             0        54.47       4.000
6433     45  19-10-2012     718125.53             0        56.47       3.969
6434     45  26-10-2012     760281.43             0        58.85       3.882

             CPI  Unemployment
0     211.096358         8.106
1     211.242170         8.106
2     211.289143         8.106
3     211.319643         8.106
4     211.350143         8.106
...          ...           ...
6430  192.013558         8.684
6431  192.170412         8.667
6432  192.327265         8.667
6433  192.330854         8.667
6434  192.308899         8.667

[6435 rows x 8 columns]>

In [10]:
df.describe

<bound method NDFrame.describe of       Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  12-02-2010    1641957.44             1        38.51       2.548
2         1  19-02-2010    1611968.17             0        39.93       2.514
3         1  26-02-2010    1409727.59             0        46.63       2.561
4         1  05-03-2010    1554806.68             0        46.50       2.625
...     ...         ...           ...           ...          ...         ...
6430     45  28-09-2012     713173.95             0        64.88       3.997
6431     45  05-10-2012     733455.07             0        64.89       3.985
6432     45  12-10-2012     734464.36             0        54.47       4.000
6433     45  19-10-2012     718125.53             0        56.47       3.969
6434     45  26-10-2012     760281.43             0        58.85       3.882

             CPI  Unemployment
0     211.096358         8.106
1     211.242170         8.106
2     211.289143         8.106
3     211.319643         8.106
4     211.350143         8.106
...          ...           ...
6430  192.013558         8.684
6431  192.170412         8.667
6432  192.327265         8.667
6433  192.330854         8.667
6434  192.308899         8.667

[6435 rows x 8 columns]>

In [11]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [71]:
df.dtypes

Store             int64
Date             object
Weekly_Sales    float64
Holiday_Flag      int64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
Year              int64
Month             int64
dtype: object

<!-- ## df['Date']=pd.to_datetime(df['Date'],format="%d-%m-%Y") -->

In [94]:
df.dtypes

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
Holiday_Flag             int64
Temperature            float64
Fuel_Price             float64
CPI                    float64
Unemployment           float64
Year                     int64
Month                    int64
dtype: object

In [33]:
df['Year']=df['Date'].dt.year

In [42]:
df['Month']=df['Date'].dt.month

In [82]:
df.dtypes

Store             int64
Date             object
Weekly_Sales    float64
Holiday_Flag      int64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
Year              int64
Month             int64
dtype: object

In [72]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3

In [83]:
df['Date']=pd.to_datetime(df['Date'],format="mixed")

In [84]:
df.dtypes

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
Holiday_Flag             int64
Temperature            float64
Fuel_Price             float64
CPI                    float64
Unemployment           float64
Year                     int64
Month                    int64
dtype: object

In [45]:
df.isnull().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Year            0
Month           0
dtype: int64

In [90]:
df.to_csv("Clean Wellmart Data_set.csv", index=False)

In [55]:
df.to_csv("E:\WALMART PROJECT\Clean Wellmart Data.csv")

In [91]:
df=pd.read_csv("Clean Wellmart Data_set.csv")

In [92]:
df.head(20)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2
1,1,2010-02-12,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2
2,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2
3,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2
4,1,2010-03-05,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3
5,1,2010-03-12,1439541.59,0,57.79,2.667,211.380643,8.106,2010,3
6,1,2010-03-19,1472515.79,0,54.58,2.720,211.215635,8.106,2010,3
7,1,2010-03-26,1404429.92,0,51.45,2.732,211.018042,8.106,2010,3
8,1,2010-04-02,1594968.28,0,62.27,2.719,210.820450,7.808,2010,4
9,1,2010-04-09,1545418.53,0,65.86,2.770,210.622857,7.808,2010,4
10,1,2010-04-16,1466058.28,0,66.32,2.808,210.488700,7.808,2010,4
11,1,2010-04-23,1391256.12,0,64.84,2.795,210.439123,7.808,2010,4
12,1,2010-04-30,1425100.71,0,67.41,2.780,210.389546,7.808,2010,4
13,1,2010-05-07,1603955.12,0,72.55,2.835,210.339968,7.808,2010,5
14,1,2010-05-14,1494251.50,0,74.78,2.854,210.337426,7.808,2010,5
15,1,2010-05-21,1399662.07,0,76.44,2.826,210.617093,7.808,2010,5
16,1,2010-05-28,1432069.95,0,80.44,2.759,210.896761,7.808,2010,5
17,1,2010-06-04,1615524.71,0,80.69,2.705,211.176428,7.808,2010,6
18,1,2010-06-11,1542561.09,0,80.43,2.668,211.456095,7.808,2010,6
19,1,2010-06-18,1503284.06,0,84.11,2.637,211.453772,7.808,2010,6

In [89]:
df.dtypes

Store             int64
Date             object
Weekly_Sales    float64
Holiday_Flag      int64
Temperature     float64
Fuel_Price      float64
CPI             float64
Unemployment    float64
Year              int64
Month             int64
dtype: object

In [102]:
df['Weekly_Sales'].mean()

np.float64(1046964.8775617715)

In [17]:
df['Weekly_Sales'].median()

960746.04

In [101]:
df['Weekly_Sales'].mode()

0        209986.25
1        213538.32
2        215359.21
3        219804.85
4        220060.35
           ...
6430    3595903.20
6431    3676388.98
6432    3749057.69
6433    3766687.43
6434    3818686.45
Name: Weekly_Sales, Length: 6435, dtype: float64

In [104]:
std=df['Weekly_Sales'].std()
m=df['Weekly_Sales'].mean()
cv=std/m
cv

np.float64(0.5390501956169006)

In [95]:
df.corr()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month
Store,1.000000e+00,1.577299e-13,-0.335332,-4.386841e-16,-0.022659,0.060023,-0.209492,0.223531,3.474318e-12,2.910676e-15
Date,1.577299e-13,1.000000e+00,0.006949,-1.328524e-02,0.145357,0.771444,0.077157,-0.248203,9.416680e-01,1.456512e-01
Weekly_Sales,-3.353320e-01,6.949360e-03,1.000000,3.689097e-02,-0.063810,0.009464,-0.072634,-0.106176,-1.837754e-02,7.614332e-02
Holiday_Flag,-4.386841e-16,-1.328524e-02,0.036891,1.000000e+00,-0.155091,-0.078347,-0.002162,0.010960,-5.678257e-02,1.229958e-01
Temperature,-2.265908e-02,1.453566e-01,-0.063810,-1.550913e-01,1.000000,0.144982,0.176888,0.101158,6.426923e-02,2.358618e-01
Fuel_Price,6.002295e-02,7.714439e-01,0.009464,-7.834652e-02,0.144982,1.000000,-0.170642,-0.034684,7.794703e-01,-4.215590e-02
CPI,-2.094919e-01,7.715746e-02,-0.072634,-2.162091e-03,0.176888,-0.170642,1.000000,-0.302020,7.479573e-02,4.979672e-03
Unemployment,2.235313e-01,-2.482029e-01,-0.106176,1.096028e-02,0.101158,-0.034684,-0.302020,1.000000,-2.418135e-01,-1.274559e-02
Year,3.474318e-12,9.416680e-01,-0.018378,-5.678257e-02,0.064269,0.779470,0.074796,-0.241813,1.000000e+00,-1.944645e-01
Month,2.910676e-15,1.456512e-01,0.076143,1.229958e-01,0.235862,-0.042156,0.004980,-0.012746,-1.944645e-01,1.000000e+00

In [105]:
df['Weekly_Sales'].skew()

np.float64(0.6683617974864524)

In [107]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment', 'Year', 'Month'],
      dtype='object')

In [5]:
df.groupby('Holiday_Flag')['Weekly_Sales'].agg(['sum','mean','std'])

                       sum          mean            std
Holiday_Flag
0             6.231919e+09  1.041256e+06  558957.436147
1             5.052996e+08  1.122888e+06  627684.931884

In [ ]:
Holiday weeks generate higher average sales but also show higher volatility compared to non-holiday weeks, 
indicating increased but less predictable consumer demand during holidays.

In [10]:
store_summary = df.groupby('Store')['Weekly_Sales'] \
    .agg(['sum','mean','std'])

store_summary.sort_values('mean', ascending=False).head(5)

                sum          mean            std
Store
20     3.013978e+08  2.107677e+06  275900.562742
4      2.995440e+08  2.094713e+06  266201.442297
14     2.889999e+08  2.020978e+06  317569.949476
13     2.865177e+08  2.003620e+06  265506.995776
2      2.753824e+08  1.925751e+06  237683.694682

In [ ]:
Store 20, 4, and 14 are the top-performing stores based on average weekly sales. 
    However, they also show higher volatility, indicating demand fluctuations. 
    Smaller stores such as Store 33 and 30 are more stable but generate significantly lower revenue.

In [11]:
store_summary = df.groupby('Store')['Weekly_Sales'] \
    .agg(['sum','mean','std'])

store_summary.sort_values('mean', ascending=True).head(5)

               sum           mean           std
Store
33     37160221.96  259861.692028  24132.927322
44     43293087.84  302748.866014  24762.832015
5      45475688.90  318011.810490  37737.965745
36     53412214.97  373511.992797  60725.173579
38     55159626.42  385731.653287  42768.169450

In [ ]:
Store 33 has the lowest average weekly sales of around 260 thousand, indicating weaker performance.

In [12]:
df.groupby('Month')['Weekly_Sales'].mean().sort_values(ascending=False)

Month
12    1.281864e+06
11    1.147266e+06
6     1.064325e+06
2     1.053200e+06
8     1.048017e+06
7     1.031748e+06
5     1.031714e+06
4     1.026762e+06
3     1.013309e+06
10    9.996321e+05
9     9.893353e+05
1     9.238846e+05
Name: Weekly_Sales, dtype: float64

In [ ]:
I performed month-wise sales analysis and observed strong seasonality. December showed the highest average sales due to holiday demand, 
while January had the lowest performance, indicating post-holiday spending decline.

In [13]:
df['Quarter'] = df['Date'].dt.quarter
df.groupby('Quarter')['Weekly_Sales'].mean()

Quarter
1    1.006136e+06
2    1.040806e+06
3    1.023251e+06
4    1.128774e+06
Name: Weekly_Sales, dtype: float64

In [ ]:
Quarter-wise analysis revealed strong seasonality, with Q4 generating the highest average sales due to festive demand, 
while Q1 showed relatively lower performance following the holiday season.

In [14]:
year_sales = df.groupby('Year')['Weekly_Sales'].mean()
year_sales.pct_change()*100

Year
2010         NaN
2011   -1.267393
2012   -1.202299
Name: Weekly_Sales, dtype: float64

In [ ]:
Year-over-year analysis showed a slight decline of approximately 1% in 2011 and 2012, 
indicating relatively stable but slightly decreasing sales performance over time.

In [25]:
!pip install sqlalchemy mysql-connector-python

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: mysql-connector-python in c:\users\ashik\appdata\roaming\python\python313\site-packages (9.5.0)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ashik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ------------------------ --------------- 1.3/2.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.3 MB/s eta 0:00:00
Downloading greenlet-3.3.2-cp313-cp313-win_amd64.whl (230 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 sqlalchemy-2.0.48

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import pandas as pd
from sqlalchemy import create_engine

# Load CSV
df = pd.read_csv(r"Clean Wellmart Data_set.csv")

# MySQL connection (UPDATED PASSWORD)
engine = create_engine(
    "mysql+mysqlconnector://root:root123@localhost:3306/wellmart_dataset"
)

# Save to MySQL
df.to_sql(
    name="wellmart",
    con=engine,
    if_exists="replace",
    index=False
)

-1